apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8050
      nodePort: 31515