apiVersion: v1

kind: Pod

metadata:

  name: cluster1-ng-1af32b9d-Node
  labels:
  component: web

spec:

  containers:

  - name: client  

    image: niteeshkumar/niteesh:image1

    ports:

    - containerPort: 8050
