apiVersion: v1

kind: Pod

metadata:

  name: client-pod
  labels:
  component: web

spec:

  containers:

  - name: client  

    image: niteeshkumar/niteesh:image1

    ports:

    - containerPort: 8050
