apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  selector:
    component: web
  type: nodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8050
      nodePort: 31515